Repository KPI-Frogs-Team/moodiverse-back, pull requests merged in 2023-04, with the labels that each got.

#2 Create flask template
  backend/backend.py
Labels: core

#4 Create API for registration
  .gitignore
  backend/backend.py
  requirements.txt
  src/backend.py
  src/config.py
  src/modules/register/functions.py
  src/modules/register/handlers.py
  src/modules/register/registration.py
Labels: core

#8 Fix registration for filling first and last name
  src/modules/register/functions.py
Labels: bug

#11 feature/create-user-endpoint
  src/backend.py
  src/modules/retrieve_user_data/functions.py
  src/modules/retrieve_user_data/handlers.py
  src/modules/retrieve_user_data/registration.py
Labels: core

#15 Create ORM database model
  requirements.txt
  src/models/database.py
Labels: core, architecture

#18 Refactor /register endpoint according to ORM database model
  src/config.py
  src/modules/register/functions.py
  src/modules/register/registration.py
Labels: core, architecture

#20 Fix: Add a random avatar choice when registering a user
  src/modules/register/functions.py
Labels: bug

#31 feature/create-login-endpoint
  requirements.txt
  src/backend.py
  src/config.py
  src/modules/login/functions.py
  src/modules/login/handlers.py
  src/modules/login/login.py
  src/modules/retrieve_user_data/functions.py
  src/modules/retrieve_user_data/registration.py
Labels: need attention, core
